import type { Doc, Folder } from "./types";
import { isoDay } from "./tasks";

const inDays = (n: number) => isoDay(new Date(Date.now() + n * 86_400_000));

export const seedFolders: Folder[] = [
  { id: "f-product", name: "Product" },
  { id: "f-engineering", name: "Engineering" },
];

export const seedDocs: Doc[] = [
  {
    id: "d-welcome",
    folderId: null,
    title: "Welcome to CoTenk",
    pinned: true,
    updatedAt: Date.now() - 1000 * 60 * 12,
    content: `Think together. Work together. CoTenk is an open workspace where people and AI agents share the same pages, the same tasks and the same context. Not another agent — the place where your tools and agents meet.

## Try it in 60 seconds

- [ ] Press Ctrl K to search, jump anywhere or ask the agent @you due:${inDays(0)}
- [ ] Type / on an empty line to insert a table, callout or chart @you
- [ ] Click **Ask agent** at the top of this page and pick "Extract action items" @devin
- [ ] Open the Marketplace and install the KPI dashboard template @you due:${inDays(3)}

## Pages are plain markdown

Every page is a markdown file at its core — readable by you, by agents and by any other tool. Click a block to edit its source, click away to see it rendered. Headings show up in the contents panel on the right.

> 💡 Tasks can have an owner and a due date: write @name and due:YYYY-MM-DD. They appear in Tasks, grouped by page or date — and you can hand any task to the agent.

## Interactive embeds

Blocks of self-contained HTML run in a sandbox, right inside the page. Agents can build them for you: charts, calculators, trackers.

<div class="w"><style>.w{display:flex;align-items:center;gap:14px;padding:6px 2px}.w button{border:1px solid var(--ck-line);background:var(--ck-panel-2);color:var(--ck-ink);border-radius:8px;padding:6px 14px;font:inherit;cursor:pointer}.w button:hover{border-color:var(--ck-accent)}.w b{font:600 28px/1 ui-monospace,monospace;color:var(--ck-accent);min-width:2ch;text-align:center}.w span{color:var(--ck-ink-3);font-size:12.5px}</style><button id="m">−</button><b id="n">3</b><button id="p">+</button><span>A tiny live widget — edit it to see the code.</span><script>var n=3,el=document.getElementById("n");document.getElementById("m").onclick=function(){el.textContent=--n};document.getElementById("p").onclick=function(){el.textContent=++n};</script></div>

## Agents work on the same files

Connect Devin CLI in Settings → Agents. It runs locally over ACP, inside your workspace folder, and edits pages directly — you watch the changes land here and can undo them with Ctrl Z.

> A workspace is not an agent. It is the place where agents and people meet.
`,
  },
  {
    id: "d-architecture",
    folderId: "f-engineering",
    title: "Sync Architecture",
    pinned: true,
    updatedAt: Date.now() - 1000 * 60 * 60 * 3,
    content: `How CoTenk keeps local files and Supabase in agreement without a conflict UI.

## Source of truth

The local file system is the working copy. Agents edit files directly. A watcher streams diffs to Supabase, which acts as the durable store and the transport between devices.

## Sync loop

1. Agent or user writes a file
2. Watcher emits a debounced change event
3. Diff is pushed to Supabase with the document revision
4. Other devices pull on focus and merge by revision

## Conflict policy

Single writer per document for now. Last write wins at the block level. Multi-user editing is deliberately out of scope for the first version.

## Open questions

How do embedded widgets get sandboxed, and which parts of a document are readable by which agent.
`,
  },
  {
    id: "d-roadmap",
    folderId: "f-product",
    title: "Roadmap Notes",
    pinned: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 26,
    content: `## Phase one

Markdown workspace with folders, documents and local state. Login through Supabase, documents sync across devices.

## Phase two

ACP integration. Devin CLI first because it supports ACP out of the box. Prompts stay local, nothing is persisted.

## Phase three

Embeds inside pages. Interactive diagrams and small widgets generated by agents, rendered in a sandboxed frame. HTML and self-contained code only, no heavy install chains.

## Later

Other agents, optionally models wired through a user supplied API key.
`,
  },
  {
    id: "d-meeting",
    folderId: "f-product",
    title: "Weekly Sync",
    pinned: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 50,
    content: `## Decisions

- Documents stay plain markdown, no proprietary block format
- Sidebar keeps a pinned section above the folder tree
- Contents panel opens per document, not globally

## Follow ups

- [ ] Prototype the block editor without persistence @you due:${inDays(-1)}
- [ ] Define the Supabase schema for docs and folders @devin
- [ ] Sketch the embed sandbox contract @team due:${inDays(5)}
`,
  },
];
